### ISSUE TITLE
Can't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by mitsuharu-morisawa** [isri-aist/hrpsys-state-observation#4]
See the result:
http://jenkinshrg.a01.aist.go.jp/job/build-ubuntu1604-64/16089/artifact/install.log

**Comment by mehdi-benallegue** [comment]
Thank you for the issue. The main repo for state-observation has changed to 
https://github.com/jrl-umi3218/state-observation

I have made this modification in the install script of drcutil
https://github.com/jenkinshrg/drcutil/pull/52#issue-529276497

Please replace it in your code also.

**Comment by mitsuharu-morisawa** [comment]
@mehdi-benallegue 
It seems to become worse.
http://jenkinshrg.a01.aist.go.jp/

**Comment by mehdi-benallegue** [comment]
I see the following error

```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library 
```

I tried a fix with commit 97f2d96

**Comment by mitsuharu-morisawa** [comment]
Thank you for the correction.
